# Generated by Django 4.2.7 on 2023-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=30)),
                ('property', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=20)),
            ],
        ),
    ]
