# Generated by Django 4.2.7 on 2023-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moving_time', models.TimeField()),
                ('current_address', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('services', models.CharField(max_length=20)),
                ('crew_size', models.IntegerField()),
                ('vehicle_size', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone_number', models.CharField(max_length=20)),
                ('relationship_to_user', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('accept_terms', models.BooleanField()),
                ('special_items', models.BooleanField()),
            ],
        ),
    ]
